
export const SET_TOTAL_PRICE = "SET_TOTAL_PRICE"

export const ADDINGREDIENT = "ADDINGREDIENT"
export const REMOVEINGRIDIENT = "REMOVEINGRIDIENT"
export const SETINGRIDIENTS = "SETINGRIDIENTS"
export const FECHING_INGRIDIENTS_FAIL = "FECHINGINGRIDIENTSFAIL"

export const PURCHSE_BURGER_START = "PURCHSE_BURGER_START"
export const PURCHSE_BURGER_SECCUSS = "PURCHSE_BURGER_SECCUSS"
export const PURCHSE_BURGER_FAIL = "PURCHSE_BURGER_FAIL"

export const FETCH_ORDER_START = "FETCH_ORDER_START"
export const FETCH_ORDER_SECCUSS = "FETCH_ORDER_SECCUSS"
export const FETCH_ORDER_FAIL = "FETCH_ORDER_FAIL"

export const AUTH_START = "AUTH_START"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAIL = "AUTH_FAIL"
export const AUTH_LOGOUT = "AUTH_LOGOUT"

export const ORDER_TO_PURCHASE = "ORDER_TO_PURCHASE"
export const CHECK_AUTH_STATE = "CHECK_AUTH_STATE"



